Add files via upload
jtr13/cc22tt pull request #112
Opened 2022-11-18 04:31 UTC by sanket-bhandari

Sanket's contribution

2022-11-23 00:15 UTC, jl6298 requested changes

2022-11-23 00:15 UTC, jl6298 commented on Misleading_Visualizations_Survey.Rmd
> +Conducted by:
Please write your names in one line. （third line）

2022-11-23 00:16 UTC, jl6298 commented on Misleading_Visualizations_Survey.Rmd
> +Conducted by:
No worry, you are not passing the submission date.

2022-12-10 00:51 UTC, jtr13 commented
@sanket-bhandari Please make the changes as requested so the PR can be merged.

2022-12-10 01:42 UTC, sanket-bhandari commented
Professor, I have created a new pull request (https://github.com/jtr13/cc22tt/pull/127) and made changes to that one.
Sorry for the trouble.

2022-12-10 02:25 UTC, jtr13 commented
Thank you for your contribution! 🎉

2022-12-10 02:25 UTC, merged