Create machine_learning_in_r.Rmd
jtr13/cc22tt pull request #71
Opened 2022-11-15 20:38 UTC by KenSu223

Adding R machine learning workflow tutorial

2022-11-15 20:42 UTC, naishadhparmar requested changes

2022-11-15 20:42 UTC, naishadhparmar commented on machine_learning_in_r.Rmd
> +---
Hi, please remove this YAML header and replace it with a header starting with a single hashtag and a single space, followed by a blank line, followed by the author's name.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/6240731/202021077-c2982986-2e66-420e-87fa-7f6434ac9279.png">

2022-11-16 20:23 UTC, KenSu223 commented
Thanks for the comment. I deleted the old file due to a read-only permission issue, and uploaded a new file with the correct header.

2022-12-09 22:30 UTC, jtr13 commented
@naishadhparmar ls this ready to be merged now?

2022-12-09 22:48 UTC, naishadhparmar commented
Hi, sorry I missed this. It seems like another group has made a community contribution with the same file name, leading to merge conflicts. Can we please change the name of this file to something else?

2022-12-12 19:30 UTC, KenSu223 commented
@jtr13 Hi Professor. It seems like our branch is still not merged. Could you please help merge it to the main? Thanks!

2022-12-13 01:42 UTC, merged

2022-12-13 01:42 UTC, jtr13 commented
Thanks for your contribution and apologies for the delay in merging! 🎉